export DOTFILES_PATH="/Users/aytordev/.dotfiles"
export DOTFILES_THEME="aytordev"
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"
export DOTLY_THEME="codely"
export ZIM_HOME="$DOTLY_PATH/modules/zimfw"
